POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "gabriel@g.com",
    "name": "Gabriel",
    "nickname": "gdmusse",
    "password": "123abc"

}

###

POST http://localhost:4000/user/login
Content-Type: application/json

{
    "nickname": "gdmusse",
    "password": "123abc"

}

###
POST http://localhost:4000/photo/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyMmUxZWRlLTQwZjAtNDRmNS1iNzZjLWY0NzA5NDk0ZTI5YiIsImlhdCI6MTYyNTUwOTU0NSwiZXhwIjoxNjI1NTE0OTQ1fQ.uBmmFiaMvwsERXnhYSkRrOo6WtOzuOyiQ7uIqvAX_DY
Content-Type: application/json

{
    "subtitle": "photo 3 subtitle",
    "file": "https://www.hostinger.com.br/tutoriais/wp-content/uploads/sites/12/2019/08/O-que-e-url.png",
    "tags": ["tag1", "tag2", "bananinha"],
    "collection": "photo collection 3"
}

###
GET http://localhost:4000/photo/all
Authorization: 

###

GET http://localhost:4000/photo/d72750f0-43fa-41c5-a745-3bdc2824d654
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyMmUxZWRlLTQwZjAtNDRmNS1iNzZjLWY0NzA5NDk0ZTI5YiIsImlhdCI6MTYyNTUwOTU0NSwiZXhwIjoxNjI1NTE0OTQ1fQ.uBmmFiaMvwsERXnhYSkRrOo6WtOzuOyiQ7uIqvAX_DY