POST http://localhost:4000/user/signup
Content-Type: application/json

{
    "email": "gabriel@g.com",
    "name": "Gabriel",
    "nickname": "gdmusse",
    "password": "123abc"

}

###

POST http://localhost:4000/user/login
Content-Type: application/json

{
    "nickname": "gdmusse",
    "password": "123abc"

}

###
POST http://localhost:4000/photo/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyMmUxZWRlLTQwZjAtNDRmNS1iNzZjLWY0NzA5NDk0ZTI5YiIsImlhdCI6MTYyNjEwNjQ4OSwiZXhwIjoxNjI2MTExODg5fQ.XdQ3kuAfzcFm25Tt9QCudTrVAhHOsQeyzq_o4efM6kA
Content-Type: application/json

{
    "subtitle": "Poison Ivy",
    "file": "https://upload.wikimedia.org/wikipedia/pt/7/7b/Detective_Comics_Vol_2_23.1_Poison_Ivy.jpg",
    "tags": ["poison ivy", "dc", "villain", "batman"]
}

###
GET http://localhost:4000/photo/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyMmUxZWRlLTQwZjAtNDRmNS1iNzZjLWY0NzA5NDk0ZTI5YiIsImlhdCI6MTYyNjIyMjQ2MSwiZXhwIjoxNjI2MjI3ODYxfQ.4LCNlL4NeGzfA71T3KRvbg1WVmfRGhcioJzXmkqCFhU

###
GET http://localhost:4000/photo/5c41cfe3-1062-4035-afda-0c2451e057aa
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyMmUxZWRlLTQwZjAtNDRmNS1iNzZjLWY0NzA5NDk0ZTI5YiIsImlhdCI6MTYyNjE5Nzc2NywiZXhwIjoxNjI2MjAzMTY3fQ.Vvshqm05vnUKXoGdAgsDHjmashJkVC6TNOUToTHOvB8

###


POST http://localhost:4000/collection/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyMmUxZWRlLTQwZjAtNDRmNS1iNzZjLWY0NzA5NDk0ZTI5YiIsImlhdCI6MTYyNjEwNjQ4OSwiZXhwIjoxNjI2MTExODg5fQ.XdQ3kuAfzcFm25Tt9QCudTrVAhHOsQeyzq_o4efM6kA
Content-Type: application/json

{
    "title": "Batman",
    "subtitle": "Characters from Batman's world",
    "image": "https://www.fundacred.org.br/site/wp-content/uploads/2017/02/batman-logo-big.gif"
}

###

POST http://localhost:4000/photo/5c41cfe3-1062-4035-afda-0c2451e057aa
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyMmUxZWRlLTQwZjAtNDRmNS1iNzZjLWY0NzA5NDk0ZTI5YiIsImlhdCI6MTYyNjExMzYzMiwiZXhwIjoxNjI2MTE5MDMyfQ.1CnbmzB9NkPVTVZmEVIVzYSMhVWz-y8LcmZDMHqbXQE
Content-Type: application/json

{
   "collection_id": "8b4356dc-21a9-4ebf-b2cb-253628e7be97"
}


###
GET http://localhost:4000/photo/search?tag=batman
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyMmUxZWRlLTQwZjAtNDRmNS1iNzZjLWY0NzA5NDk0ZTI5YiIsImlhdCI6MTYyNjE5Nzc2NywiZXhwIjoxNjI2MjAzMTY3fQ.Vvshqm05vnUKXoGdAgsDHjmashJkVC6TNOUToTHOvB8

